spring:
  application:
    name: Recipe
  datasource:
    url: jdbc:mysql://localhost:3306/recipe
    username: root
    password: 1234
    spring:
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt-secret: tempRandomStringforDevelopmentPurposes_123456789123456789
  jwt-expiration-milliseconds: 86400000